apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sandbox-namespace

resources:
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/name: content-scanner
      app.kubernetes.io/part-of: sandbox-platform
    includeSelectors: false
